/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'un compte */
        get: operations["findById"];
        /** Mise à jour du rôle, nom et prénom */
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put: operations["modifier"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employes/{id}/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["remplacerDocument"];
        post?: never;
        delete: operations["supprimerDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/departements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["modifier_1"];
        post?: never;
        delete: operations["desactiver"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste tous les comptes */
        get: operations["findAll"];
        put?: never;
        /** Création d'un compte admin ou manager */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pointages/{id}/corriger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["corrigerManuellement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pointages/qr-code/generer/{employeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["genererQrCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kiosque/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["scanner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/previsualiser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["previsualiser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/executer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["executer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/analyser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["analyser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/horaires-reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lister"];
        put?: never;
        post: operations["creer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lister_1"];
        put?: never;
        post: operations["creer_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employes/{id}/transferer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transferer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employes/{id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recupererPhoto"];
        put?: never;
        post: operations["televerserPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employes/{id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listerDocuments"];
        put?: never;
        post: operations["attacherDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employes/{id}/desactiver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["desactiver_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employes/{id}/carte/envoyer-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["envoyerCarteParEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employes/{employeId}/teletravail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lister_2"];
        put?: never;
        post: operations["creer_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/departements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lister_3"];
        put?: never;
        post: operations["creer_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/departements/{id}/activer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["activer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Réinitialisation du mot de passe */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Déconnexion */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connexion utilisateur */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demande de réinitialisation de mot de passe */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anomalies/{id}/resoudre": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["marquerResolue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Désactivation d'un compte (+ révocation des sessions) */
        patch: operations["deactivate"];
        trace?: never;
    };
    "/api/users/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Réactivation d'un compte */
        patch: operations["activate"];
        trace?: never;
    };
    "/api/pointages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lister_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pointages/qr-code/{employeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["qrCodeActif"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pointages/employe/{employeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listerParEmploye"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/historique": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["historique"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/historique/{lotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detailLot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employes/{id}/transferts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["historiqueTransferts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employes/{id}/documents/{documentId}/telecharger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["telechargerDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profil de l'utilisateur connecté */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lister_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employes/{employeId}/teletravail/{planningId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["supprimer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserUpdateRequest: {
            /** @enum {string} */
            role: "admin" | "manager";
            nom: string;
            prenom: string;
        };
        ApiResponseUserResponse: {
            success?: boolean;
            data?: components["schemas"]["UserResponse"];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        UserResponse: {
            /** Format: uuid */
            id?: string;
            email?: string;
            /** @enum {string} */
            role?: "admin" | "manager";
            nom?: string;
            prenom?: string;
            /** @enum {string} */
            statut?: "actif" | "inactif";
            /** Format: date-time */
            creeLe?: string;
            /** Format: date-time */
            modifieLe?: string;
        };
        EmployeModificationRequete: {
            nom: string;
            prenom: string;
            email?: string;
            telephone?: string;
            poste?: string;
            /** Format: date */
            dateEmbauche: string;
            /** @enum {string} */
            typeContrat: "CDI" | "CDD" | "STAGIAIRE" | "STAGIAIRE_REMUNERE";
            /** Format: date */
            dateFinContratPrevue?: string;
        };
        ApiResponseEmployeReponse: {
            success?: boolean;
            data?: components["schemas"]["EmployeReponse"];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        EmployeReponse: {
            /** Format: uuid */
            id?: string;
            nom?: string;
            prenom?: string;
            email?: string;
            telephone?: string;
            poste?: string;
            /** Format: uuid */
            departementId?: string;
            departementNom?: string;
            /** Format: uuid */
            managerId?: string;
            /** Format: date */
            dateEmbauche?: string;
            typeContrat?: string;
            /** Format: date */
            dateFinContratPrevue?: string;
            /** Format: date */
            dateDepart?: string;
            motifDepart?: string;
            statut?: string;
            /** Format: uuid */
            photoFichierId?: string;
            /** Format: date-time */
            creeLe?: string;
            /** Format: date-time */
            modifieLe?: string;
        };
        ApiResponseEmployeDocumentReponse: {
            success?: boolean;
            data?: components["schemas"]["EmployeDocumentReponse"];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        EmployeDocumentReponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            fichierId?: string;
            nomOriginal?: string;
            typeMime?: string;
            typeDocument?: string;
            /** Format: date-time */
            creeLe?: string;
        };
        DepartementRequete: {
            nom: string;
            /** Format: uuid */
            managerId?: string;
        };
        ApiResponseDepartementReponse: {
            success?: boolean;
            data?: components["schemas"]["DepartementReponse"];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        DepartementReponse: {
            /** Format: uuid */
            id?: string;
            nom?: string;
            /** Format: uuid */
            managerId?: string;
            statut?: string;
            /** Format: date-time */
            creeLe?: string;
            /** Format: date-time */
            modifieLe?: string;
        };
        UserCreateRequest: {
            /** Format: email */
            email: string;
            motDePasse: string;
            /** @enum {string} */
            role: "admin" | "manager";
            nom: string;
            prenom: string;
        };
        CorrectionPointageRequete: {
            /** Format: date-time */
            nouvelHorodatage: string;
            motif: string;
        };
        ApiResponsePointageReponse: {
            success?: boolean;
            data?: components["schemas"]["PointageReponse"];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        PointageReponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            employeId?: string;
            /** @enum {string} */
            typeScan?: "entree" | "sortie";
            /** Format: date-time */
            horodatage?: string;
            corrigeManuellement?: boolean;
            motifCorrection?: string;
        };
        ApiResponseQrCodeReponse: {
            success?: boolean;
            data?: components["schemas"]["QrCodeReponse"];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        QrCodeReponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            employeId?: string;
            valeur?: string;
            actif?: boolean;
            bloque?: boolean;
            /** Format: date-time */
            genereLe?: string;
        };
        ScanRequete: {
            valeurQr: string;
            /** @enum {string} */
            typeScan: "entree" | "sortie";
        };
        ApiResponseImportApercuReponse: {
            success?: boolean;
            data?: components["schemas"]["ImportApercuReponse"];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ImportApercuReponse: {
            entetes?: string[];
            apercuLignes?: string[][];
            /** Format: int32 */
            totalLignes?: number;
            champsCible?: components["schemas"]["ImportChampSpecReponse"][];
            mappingSuggere?: {
                [key: string]: number;
            };
        };
        ImportChampSpecReponse: {
            cle?: string;
            libelle?: string;
            requis?: boolean;
            type?: string;
        };
        ApiResponseImportRapportReponse: {
            success?: boolean;
            data?: components["schemas"]["ImportRapportReponse"];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ImportLigneReponse: {
            /** Format: int32 */
            numeroLigne?: number;
            statut?: string;
            action?: string;
            donnees?: components["schemas"]["JsonNode"];
            erreurs?: string[];
            /** Format: uuid */
            entiteId?: string;
        };
        ImportRapportReponse: {
            /** Format: uuid */
            lotId?: string;
            cible?: string;
            mode?: string;
            /** Format: int32 */
            totalLignes?: number;
            /** Format: int32 */
            lignesValides?: number;
            /** Format: int32 */
            lignesErreur?: number;
            lignes?: components["schemas"]["ImportLigneReponse"][];
        };
        JsonNode: unknown;
        HoraireReferenceRequete: {
            heureDebutMatin: string;
            heureFinMatin: string;
            heureDebutApresMidi: string;
            heureFinApresMidi: string;
            /** Format: int32 */
            toleranceMinutes?: number;
            /** Format: date */
            dateEffet: string;
        };
        ApiResponseHoraireReferenceReponse: {
            success?: boolean;
            data?: components["schemas"]["HoraireReferenceReponse"];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        HoraireReferenceReponse: {
            /** Format: uuid */
            id?: string;
            heureDebutMatin?: string;
            heureFinMatin?: string;
            heureDebutApresMidi?: string;
            heureFinApresMidi?: string;
            /** Format: int32 */
            toleranceMinutes?: number;
            /** Format: date */
            dateEffet?: string;
        };
        EmployeRequete: {
            nom: string;
            prenom: string;
            email?: string;
            telephone?: string;
            poste?: string;
            /** Format: uuid */
            departementId: string;
            /** Format: uuid */
            managerId?: string;
            /** Format: date */
            dateEmbauche: string;
            /** @enum {string} */
            typeContrat: "CDI" | "CDD" | "STAGIAIRE" | "STAGIAIRE_REMUNERE";
            /** Format: date */
            dateFinContratPrevue?: string;
        };
        TransfertRequete: {
            /** Format: uuid */
            nouveauDepartementId: string;
            /** Format: uuid */
            nouveauManagerId?: string;
            /** Format: date */
            dateEffet: string;
        };
        DesactivationRequete: {
            /** @enum {string} */
            motif: "demission" | "licenciement" | "fin_cdd" | "rupture" | "autre";
            /** Format: date */
            dateDepart: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            data?: unknown;
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        CarteEmailRequete: {
            objet: string;
            corps: string;
            destinataire?: string;
        };
        PlanningTeletravailRequete: {
            /** Format: date */
            dateDebut: string;
            /** Format: date */
            dateFin?: string;
            jours: ("lundi" | "mardi" | "mercredi" | "jeudi" | "vendredi" | "samedi" | "dimanche")[];
        };
        ApiResponsePlanningTeletravailReponse: {
            success?: boolean;
            data?: components["schemas"]["PlanningTeletravailReponse"];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        PlanningTeletravailReponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            employeId?: string;
            /** Format: date */
            dateDebut?: string;
            /** Format: date */
            dateFin?: string;
            jours?: ("lundi" | "mardi" | "mercredi" | "jeudi" | "vendredi" | "samedi" | "dimanche")[];
            /** Format: date-time */
            creeLe?: string;
        };
        ResetPasswordRequest: {
            token: string;
            nouveauMotDePasse: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            motDePasse: string;
        };
        ApiResponseLoginResponse: {
            success?: boolean;
            data?: components["schemas"]["LoginResponse"];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        LoginResponse: {
            token?: string;
            user?: components["schemas"]["UserResponse"];
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        AnomaliePointageReponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            employeId?: string;
            /** Format: date */
            datePointage?: string;
            /** @enum {string} */
            typeAnomalie?: "retard" | "depart_anticipe" | "absence_checkout" | "presence_incomplete";
            resolue?: boolean;
            /** Format: date-time */
            creeLe?: string;
        };
        ApiResponseAnomaliePointageReponse: {
            success?: boolean;
            data?: components["schemas"]["AnomaliePointageReponse"];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListUserResponse: {
            success?: boolean;
            data?: components["schemas"]["UserResponse"][];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        ApiResponsePagedResponsePointageReponse: {
            success?: boolean;
            data?: components["schemas"]["PagedResponsePointageReponse"];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        PagedResponsePointageReponse: {
            content?: components["schemas"]["PointageReponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            last?: boolean;
        };
        ApiResponsePagedResponseImportLotReponse: {
            success?: boolean;
            data?: components["schemas"]["PagedResponseImportLotReponse"];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ImportLotReponse: {
            /** Format: uuid */
            id?: string;
            cible?: string;
            mode?: string;
            nomFichier?: string;
            /** Format: int32 */
            nbLignesTotal?: number;
            /** Format: int32 */
            nbLignesValides?: number;
            /** Format: int32 */
            nbLignesErreur?: number;
            /** Format: uuid */
            executePar?: string;
            /** Format: date-time */
            creeLe?: string;
        };
        PagedResponseImportLotReponse: {
            content?: components["schemas"]["ImportLotReponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            last?: boolean;
        };
        ApiResponseListHoraireReferenceReponse: {
            success?: boolean;
            data?: components["schemas"]["HoraireReferenceReponse"][];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponsePagedResponseEmployeReponse: {
            success?: boolean;
            data?: components["schemas"]["PagedResponseEmployeReponse"];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        PagedResponseEmployeReponse: {
            content?: components["schemas"]["EmployeReponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            last?: boolean;
        };
        ApiResponseListEmployeTransfertReponse: {
            success?: boolean;
            data?: components["schemas"]["EmployeTransfertReponse"][];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        EmployeTransfertReponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            ancienDepartementId?: string;
            /** Format: uuid */
            nouveauDepartementId?: string;
            /** Format: uuid */
            ancienManagerId?: string;
            /** Format: uuid */
            nouveauManagerId?: string;
            /** Format: date */
            dateEffet?: string;
            /** Format: date-time */
            creeLe?: string;
        };
        ApiResponseListEmployeDocumentReponse: {
            success?: boolean;
            data?: components["schemas"]["EmployeDocumentReponse"][];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListPlanningTeletravailReponse: {
            success?: boolean;
            data?: components["schemas"]["PlanningTeletravailReponse"][];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListDepartementReponse: {
            success?: boolean;
            data?: components["schemas"]["DepartementReponse"][];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponsePagedResponseAnomaliePointageReponse: {
            success?: boolean;
            data?: components["schemas"]["PagedResponseAnomaliePointageReponse"];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        PagedResponseAnomaliePointageReponse: {
            content?: components["schemas"]["AnomaliePointageReponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            last?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserResponse"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEmployeReponse"];
                };
            };
        };
    };
    modifier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeModificationRequete"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEmployeReponse"];
                };
            };
        };
    };
    remplacerDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    fichier: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEmployeDocumentReponse"];
                };
            };
        };
    };
    supprimerDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    modifier_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartementRequete"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDepartementReponse"];
                };
            };
        };
    };
    desactiver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListUserResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserResponse"];
                };
            };
        };
    };
    corrigerManuellement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionPointageRequete"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePointageReponse"];
                };
            };
        };
    };
    genererQrCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQrCodeReponse"];
                };
            };
        };
    };
    scanner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequete"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePointageReponse"];
                };
            };
        };
    };
    previsualiser: {
        parameters: {
            query: {
                cible: "DEPARTEMENTS" | "EMPLOYES" | "SOLDES_CONGES_INITIAUX";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    fichier: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseImportApercuReponse"];
                };
            };
        };
    };
    executer: {
        parameters: {
            query: {
                cible: "DEPARTEMENTS" | "EMPLOYES" | "SOLDES_CONGES_INITIAUX";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    fichier: string;
                    mapping: {
                        [key: string]: number;
                    };
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseImportRapportReponse"];
                };
            };
        };
    };
    analyser: {
        parameters: {
            query: {
                cible: "DEPARTEMENTS" | "EMPLOYES" | "SOLDES_CONGES_INITIAUX";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    fichier: string;
                    mapping: {
                        [key: string]: number;
                    };
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseImportRapportReponse"];
                };
            };
        };
    };
    lister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListHoraireReferenceReponse"];
                };
            };
        };
    };
    creer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoraireReferenceRequete"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseHoraireReferenceReponse"];
                };
            };
        };
    };
    lister_1: {
        parameters: {
            query: {
                departementId?: string;
                managerId?: string;
                typeContrat?: "CDI" | "CDD" | "STAGIAIRE" | "STAGIAIRE_REMUNERE";
                statut?: "actif" | "inactif";
                recherche?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePagedResponseEmployeReponse"];
                };
            };
        };
    };
    creer_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeRequete"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEmployeReponse"];
                };
            };
        };
    };
    transferer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransfertRequete"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEmployeReponse"];
                };
            };
        };
    };
    recupererPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    televerserPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    photo: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEmployeReponse"];
                };
            };
        };
    };
    listerDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListEmployeDocumentReponse"];
                };
            };
        };
    };
    attacherDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    fichier: string;
                    typeDocument?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEmployeDocumentReponse"];
                };
            };
        };
    };
    desactiver_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesactivationRequete"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    envoyerCarteParEmail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarteEmailRequete"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    lister_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPlanningTeletravailReponse"];
                };
            };
        };
    };
    creer_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanningTeletravailRequete"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePlanningTeletravailReponse"];
                };
            };
        };
    };
    lister_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListDepartementReponse"];
                };
            };
        };
    };
    creer_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartementRequete"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDepartementReponse"];
                };
            };
        };
    };
    activer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDepartementReponse"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLoginResponse"];
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    marquerResolue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAnomaliePointageReponse"];
                };
            };
        };
    };
    deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserResponse"];
                };
            };
        };
    };
    activate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserResponse"];
                };
            };
        };
    };
    lister_4: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePagedResponsePointageReponse"];
                };
            };
        };
    };
    qrCodeActif: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQrCodeReponse"];
                };
            };
        };
    };
    listerParEmploye: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                employeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePagedResponsePointageReponse"];
                };
            };
        };
    };
    historique: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePagedResponseImportLotReponse"];
                };
            };
        };
    };
    detailLot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseImportRapportReponse"];
                };
            };
        };
    };
    historiqueTransferts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListEmployeTransfertReponse"];
                };
            };
        };
    };
    telechargerDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserResponse"];
                };
            };
        };
    };
    lister_5: {
        parameters: {
            query: {
                resolue?: boolean;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePagedResponseAnomaliePointageReponse"];
                };
            };
        };
    };
    supprimer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employeId: string;
                planningId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
}
