/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/employes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put: operations["modifier"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/departements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["modifier_1"];
        post?: never;
        delete: operations["desactiver"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lister"];
        put?: never;
        post: operations["creer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employes/{id}/transferer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transferer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employes/{id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listerDocuments"];
        put?: never;
        post: operations["attacherDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employes/{id}/desactiver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["desactiver_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/departements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lister_1"];
        put?: never;
        post: operations["creer_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/departements/{id}/activer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["activer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employes/{id}/transferts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["historiqueTransferts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employes/{id}/documents/{documentId}/telecharger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["telechargerDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EmployeModificationRequete: {
            nom: string;
            prenom: string;
            email?: string;
            telephone?: string;
            poste?: string;
            /** Format: date */
            dateEmbauche: string;
            /** @enum {string} */
            typeContrat: "CDI" | "CDD" | "STAGIAIRE" | "STAGIAIRE_REMUNERE";
            /** Format: date */
            dateFinContratPrevue?: string;
        };
        ApiResponseEmployeReponse: {
            success?: boolean;
            data?: components["schemas"]["EmployeReponse"];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        EmployeReponse: {
            /** Format: uuid */
            id?: string;
            nom?: string;
            prenom?: string;
            email?: string;
            telephone?: string;
            poste?: string;
            /** Format: uuid */
            departementId?: string;
            departementNom?: string;
            /** Format: uuid */
            managerId?: string;
            /** Format: date */
            dateEmbauche?: string;
            typeContrat?: string;
            /** Format: date */
            dateFinContratPrevue?: string;
            /** Format: date */
            dateDepart?: string;
            motifDepart?: string;
            statut?: string;
            /** Format: date-time */
            creeLe?: string;
            /** Format: date-time */
            modifieLe?: string;
        };
        DepartementRequete: {
            nom: string;
            /** Format: uuid */
            managerId?: string;
        };
        ApiResponseDepartementReponse: {
            success?: boolean;
            data?: components["schemas"]["DepartementReponse"];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        DepartementReponse: {
            /** Format: uuid */
            id?: string;
            nom?: string;
            /** Format: uuid */
            managerId?: string;
            statut?: string;
            /** Format: date-time */
            creeLe?: string;
            /** Format: date-time */
            modifieLe?: string;
        };
        EmployeRequete: {
            nom: string;
            prenom: string;
            email?: string;
            telephone?: string;
            poste?: string;
            /** Format: uuid */
            departementId: string;
            /** Format: uuid */
            managerId?: string;
            /** Format: date */
            dateEmbauche: string;
            /** @enum {string} */
            typeContrat: "CDI" | "CDD" | "STAGIAIRE" | "STAGIAIRE_REMUNERE";
            /** Format: date */
            dateFinContratPrevue?: string;
        };
        TransfertRequete: {
            /** Format: uuid */
            nouveauDepartementId: string;
            /** Format: uuid */
            nouveauManagerId?: string;
            /** Format: date */
            dateEffet: string;
        };
        ApiResponseEmployeDocumentReponse: {
            success?: boolean;
            data?: components["schemas"]["EmployeDocumentReponse"];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        EmployeDocumentReponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            fichierId?: string;
            nomOriginal?: string;
            typeMime?: string;
            typeDocument?: string;
            /** Format: date-time */
            creeLe?: string;
        };
        DesactivationRequete: {
            /** @enum {string} */
            motif: "demission" | "licenciement" | "fin_cdd" | "rupture" | "autre";
            /** Format: date */
            dateDepart: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            data?: unknown;
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        ApiResponsePagedResponseEmployeReponse: {
            success?: boolean;
            data?: components["schemas"]["PagedResponseEmployeReponse"];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        PagedResponseEmployeReponse: {
            content?: components["schemas"]["EmployeReponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            last?: boolean;
        };
        ApiResponseListEmployeTransfertReponse: {
            success?: boolean;
            data?: components["schemas"]["EmployeTransfertReponse"][];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        EmployeTransfertReponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            ancienDepartementId?: string;
            /** Format: uuid */
            nouveauDepartementId?: string;
            /** Format: uuid */
            ancienManagerId?: string;
            /** Format: uuid */
            nouveauManagerId?: string;
            /** Format: date */
            dateEffet?: string;
            /** Format: date-time */
            creeLe?: string;
        };
        ApiResponseListEmployeDocumentReponse: {
            success?: boolean;
            data?: components["schemas"]["EmployeDocumentReponse"][];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListDepartementReponse: {
            success?: boolean;
            data?: components["schemas"]["DepartementReponse"][];
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEmployeReponse"];
                };
            };
        };
    };
    modifier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeModificationRequete"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEmployeReponse"];
                };
            };
        };
    };
    modifier_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartementRequete"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDepartementReponse"];
                };
            };
        };
    };
    desactiver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    lister: {
        parameters: {
            query: {
                departementId?: string;
                managerId?: string;
                typeContrat?: "CDI" | "CDD" | "STAGIAIRE" | "STAGIAIRE_REMUNERE";
                statut?: "actif" | "inactif";
                recherche?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePagedResponseEmployeReponse"];
                };
            };
        };
    };
    creer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeRequete"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEmployeReponse"];
                };
            };
        };
    };
    transferer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransfertRequete"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEmployeReponse"];
                };
            };
        };
    };
    listerDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListEmployeDocumentReponse"];
                };
            };
        };
    };
    attacherDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    fichier: string;
                    typeDocument?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEmployeDocumentReponse"];
                };
            };
        };
    };
    desactiver_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesactivationRequete"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    lister_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListDepartementReponse"];
                };
            };
        };
    };
    creer_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartementRequete"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDepartementReponse"];
                };
            };
        };
    };
    activer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDepartementReponse"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    historiqueTransferts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListEmployeTransfertReponse"];
                };
            };
        };
    };
    telechargerDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
}
